# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - customgptapp2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Guardrails install validators (from Hub)
        env:
          GUARDRAILS_API_KEY: ${{ secrets.GUARDRAILS_API_KEY }}
          GUARDRAILS_CLI_TOKEN: ${{ secrets.GUARDRAILS_API_KEY }}
        run: |
          source venv/bin/activate
          pip install guardrails-ai
          # Authenticate CLI
          guardrails configure --disable-metrics --disable-remote-inferencing --token "${GUARDRAILS_API_KEY}"
          # Install validators into local venv, now part of deployment artifact!
          guardrails hub install hub://guardrails/detect_jailbreak
          guardrails hub install hub://guardrails/toxic_language
          guardrails hub install hub://guardrails/secrets_present
          guardrails hub install hub://guardrails/guardrails_pii

      - name: Zip artifact for deployment
        # Include venv so installed hub packages go to production!
        run: zip -r release.zip . -x "venv/*/__pycache__/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'customgptapp2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_65DFE814F19B4CCDB75CDA886F89C02D }}
